# Generated by Django 5.2.17 on 2026-09-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swirl', '0006_searchprovider_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='querytransform',
            options={'verbose_name': 'QueryTransform', 'verbose_name_plural': 'QueryTransforms'},
        ),
        migrations.AlterModelOptions(
            name='searchprovider',
            options={'ordering': ['id'], 'verbose_name': 'SearchProvider', 'verbose_name_plural': 'SearchProviders'},
        ),
    ]
