# Site settings
title: SWIRL AI Documentation
description: "Powerful Real-Time AI Infrastructure Software"
repository: "swirlai/swirl-search"
url: https://docs.swirlaiconnect.com
baseurl: "" # the subpath of your site, e.g. /blog

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/swirl-logo.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Heading anchor links appear on hover over h1-h6 tags in page content
heading_anchors: true

# For copy button on code
enable_copy_code_button: true

# External navigation links
nav_external_links:
  - title: SWIRL on GitHub
    url: https://github.com/swirlai/swirl-search
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: SWIRL AI Connect
    url: https://swirlaiconnect.com/
    hide_icon: false # set to true to hide the external link icon - defaults to false
nav_external_links_new_tab: true # set to true to open all external links in new tabs

# Aux links for the upper right navigation
aux_links:
  "SWIRL AI on GitHub":
    - "//github.com/swirlai/swirl-search"
aux_links_new_tab: true # Makes Aux links open in a new tab. Default is false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

callouts_level: loud # or quiet
callouts:
  highlight:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 3
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

relative_links:
  enabled:     true
  collections: false

# Build settings
markdown: kramdown
theme: just-the-docs
plugins:
  - jekyll-default-layout
  - jekyll-relative-links
  - jemoji
disable_disk_cache: true

exclude:
 # Modified from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

# Kramdown settings
kramdown:
  smart_quotes: [apos, apos, quot, quot]

# Plugins
plugins:
  - jekyll-sass-converter

# Just the Docs settings
just_the_docs:
  # other settings...
  auxiliary_stylesheets: ["_sass/custom/custom.scss"]

# Quiet the deprecation warnings from the 'sass-embedded' gem
sass:
  quiet_deps: true
  silence_deprecations: ['import']
