source "https://rubygems.org"

gem "jekyll", "~> 4.4.1" # installed by `gem jekyll`
gem "jekyll-default-layout"
gem "jekyll-relative-links"
gem "jemoji"
gem "just-the-docs", "0.10.1"
gem 'jekyll-sass-converter', '~> 3.1.0' # Quiet the deprecation warnings from the 'sass-embedded' gem

