import logging
import threading

from rest_framework.request import Request

from swirl.exceptions import RagError
from swirl.models import Result
from swirl.processors import *

logger = logging.getLogger(__name__)

instances = {}

# Per-search-id locks to serialize concurrent detail-search-rag calls.
# Galaxy has been observed firing /sapi/detail-search-rag/ twice for a single
# user action (sometimes against the same search_id, sometimes against two
# duplicate Search rows). Without serialization both requests cache-miss
# simultaneously, each spins up its own RAGPostResultProcessor, each issues
# an independent OpenAI completion, both save Result rows, and the user sees
# the AI Summary appear and then swap to a different one as the UI re-reads
# the second one. Serializing on search_id makes the second caller block
# until the first writes its Result, then serve the cached body — one
# completion per search_id, one summary visible to the user.
_rag_locks: dict[str, threading.Lock] = {}
_rag_locks_master = threading.Lock()


def _get_rag_lock(search_id) -> threading.Lock:
    """Return (creating if needed) the lock for a given search_id."""
    key = str(search_id) if search_id is not None else ""
    with _rag_locks_master:
        lock = _rag_locks.get(key)
        if lock is None:
            lock = threading.Lock()
            _rag_locks[key] = lock
        return lock


class SearchRag:

    def __init__(self, request_data: Request) -> None:
        request_data = request_data.GET.dict()
        logger.debug(f"{self}: init search rag {request_data}")
        self.search_id = request_data.get("search_id", None)

        # Parse query parameters
        self.rag_query_items = []
        rag_query_items = request_data.get("rag_items", None)

        if rag_query_items and isinstance(rag_query_items, str):
            self.rag_query_items = rag_query_items.split(",")

        # DS-5598: extract rag_timeout from the URL query and forward it
        # down to the RAG processor. The TimeoutMiddleware's
        # func_timeout wrapper can't actually interrupt a blocking
        # OpenAI HTTP call, so the documented rag_timeout URL param was
        # silently ignored — the rag.feature:240 scenario waited the
        # full RAG response time and never saw the timeout-error
        # message. Plumbing the value to the OpenAI client makes the
        # timeout fire for real.
        self.rag_timeout = None
        rag_timeout_raw = request_data.get("rag_timeout")
        if rag_timeout_raw:
            try:
                self.rag_timeout = int(rag_timeout_raw)
            except (TypeError, ValueError):
                self.rag_timeout = None

        # Free-form user-supplied guidance for the RAG response. Galaxy
        # sends this via the "Optional instructions for the AI Response..."
        # textarea as ?ai_instructions=...; before this wiring the backend
        # silently dropped it. We trim and bound the value to keep a
        # malicious / accidental megabyte payload from blowing up the
        # prompt budget — RAG_MAX_TOKENS is the real backstop but a cheap
        # upfront cap is cleaner than letting RagPrompt see truncated
        # mid-sentence text.
        ai_instructions_raw = request_data.get("ai_instructions", "") or ""
        self.ai_instructions = ai_instructions_raw.strip()[:2000]

    def _extract_result(self, json_result: dict) -> tuple:
        """Return (body_text, additional_content) from a stored rag json_result."""
        body = json_result.get("body", [None])
        body_text = body[0] if isinstance(body, (list, tuple)) else body
        additional_content = json_result.get("additional_content", {})
        return body_text, additional_content

    def _try_serve_cache(self) -> tuple | None:
        """Cache-only check. Returns the cached body+content tuple, or None on miss.

        An empty ``self.rag_query_items`` means the caller did NOT pass
        ``?rag_items=…`` — treat that as "no filter requested, serve whatever's
        stored" rather than "items changed, regenerate". Previously the latter
        interpretation caused every detail-search-rag fetch to delete-and-
        recreate the Result generated by the auto-RAG path (swirl/search.py:302),
        so the user saw one summary appear and then a different summary
        replace it seconds later (fixed in 4.5.0.5).
        """
        try:
            rag_result = Result.objects.get(
                search_id=self.search_id, searchprovider="ChatGPT"
            )
        except Result.DoesNotExist:
            return None

        stored_items = set(rag_result.json_results[0].get("rag_query_items") or [])
        requested_items = set(self.rag_query_items)
        if not requested_items or requested_items == stored_items:
            body_text, additional_content = self._extract_result(rag_result.json_results[0])
            if body_text:
                return body_text, additional_content
            return False, {}
        return None

    def get_rag_result(self) -> tuple:
        # Fast path: already-cached Result with matching items → serve and
        # return without taking the lock. Hot path; lock-free.
        cached = self._try_serve_cache()
        if cached is not None:
            return cached

        # Slow path: serialize concurrent generators for this search_id so
        # only one OpenAI completion runs and one Result is written. The
        # second caller blocks here, re-checks the cache after acquiring
        # the lock (the first writer's Result is now stored), and serves it.
        lock = _get_rag_lock(self.search_id)
        with lock:
            cached = self._try_serve_cache()
            if cached is not None:
                logger.debug(
                    f"RAG: search_id={self.search_id} served cached result "
                    f"after waiting on in-flight generation"
                )
                return cached

            rag_processor = RAGPostResultProcessor(
                search_id=self.search_id,
                request_id="",
                should_get_results=True,
                rag_query_items=self.rag_query_items,
                rag_timeout=self.rag_timeout,
                ai_instructions=self.ai_instructions,
            )
            instances[self.search_id] = rag_processor
            if rag_processor.validate():
                result = rag_processor.process(should_return=True)
                if result == 0:
                    # DS-5598: when ``rag_timeout`` was passed and the OpenAI
                    # call raised — most commonly an APITimeoutError because
                    # the per-request timeout fired — surface the
                    # timeout-specific message so Galaxy's AI Summary footer
                    # contains the documented "No response from Generative
                    # AI" string the rag.feature:240 scenario asserts on.
                    # Without this branch the test sees the generic
                    # credentials message and fails.
                    if self.rag_timeout is not None:
                        return (
                            f"Timeout: No response from Generative AI within "
                            f"{self.rag_timeout}s.",
                            {},
                        )
                    return "Please check the OpenAI or Azure OpenAI credentials in your environment.", {}

                if self.search_id in instances:
                    del instances[self.search_id]

                return self._extract_result(result.json_results[0])

            return "", {}

    def process_rag(self) -> dict:
        body_text = ""
        additional_content = {}
        try:
            result = self.get_rag_result()
            if isinstance(result, tuple):
                body_text, additional_content = result
            else:
                body_text = result
        except RagError as err:
            logger.error(f"{self}: Rag Error {err}")

        return {"message": body_text, "additional_content": additional_content}
